force-app/main/default/objects/UserSettings__c/UserSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>These settings impact the user experience</description>
    <label>Metadata Tracker User Settings</label>
</CustomObject>

force-app/main/default/objects/UserSettings__c/fields/MaxResultSize__c.field-meta.xml
<CustomField>
    <fullName>MaxResultSize__c</fullName>
    <defaultValue>5000</defaultValue>
    <description>The maximum number of rows of data that will be sent to the controller to see if the pieces of metadata are being tracked. In large orgs you may need to reduce this number to prevent heap size limit errors from occurring.</description>
    <inlineHelpText>The maximum number of rows of data that will be sent to the controller to see if the pieces of metadata are being tracked. In large orgs you may need to reduce this number to prevent heap size limit errors from occurring.</inlineHelpText>
    <label>Max Result Size</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PostInstallHandlerTest.cls
@isTest
public class PostInstallHandlerTest {

    @isTest
    static void testInstallScript() {
        Test.setMock(HttpCalloutMock.class, new IssueServiceMock());
        Test.startTest();
        UserSettings__c settings = UserSettings__c.getOrgDefaults();
        System.assertEquals(null, settings.Id);
        System.assertEquals(null, settings.MaxResultSize__c);
        try{
            PostInstallHandler postinstall = new PostInstallHandler();
            Test.testInstall(postinstall, null);
        } catch(Exception e) {
            System.assert(false);
        }
        Test.StopTest();
        settings = UserSettings__c.getOrgDefaults();
        System.assert(true);
        System.assertNotEquals(null, settings.Id);
        System.assertEquals(5000, settings.MaxResultSize__c);
    }

}