force-app/main/default/objects/UserSettings__c/UserSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>These settings impact the user experience</description>
    <label>Metadata Tracker User Settings</label>
</CustomObject>

force-app/main/default/objects/UserSettings__c/fields/MaxResultSize__c.field-meta.xml
<CustomField>
    <fullName>MaxResultSize__c</fullName>
    <defaultValue>5000</defaultValue>
    <description>The maximum number of rows of data that will be sent to the controller to see if the pieces of metadata are being tracked. In large orgs you may need to reduce this number to prevent heap size limit errors from occurring.</description>
    <inlineHelpText>The maximum number of rows of data that will be sent to the controller to see if the pieces of metadata are being tracked. In large orgs you may need to reduce this number to prevent heap size limit errors from occurring.</inlineHelpText>
    <label>Max Result Size</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserSettings__c/fields/TrackChildrenUnderParent__c.field-meta.xml
<CustomField>
    <fullName>TrackChildrenUnderParent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to track all children metadata types under their parent (e.g. custom object)</description>
    <inlineHelpText>Check this to track all children metadata types under their parent (e.g. custom object)</inlineHelpText>
    <label>Track Children Under Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomSettingsUtility.cls
public with sharing class CustomSettingsUtility {

    public static UserSettings__c createDefaultCustomSettingRecord(Boolean isInsert) {
        UserSettings__c settings = UserSettings__c.getOrgDefaults();
        if(settings.Id == null) {
            settings = new UserSettings__c();
        }
        settings.MaxResultSize__c = 5000;
        settings.TrackChildrenUnderParent__c = false;
        if(isInsert) {
            upsert settings;
        }
        return settings;
    }

}